#!/usr/bin/env python3
"""
Start the minilog-web-viewer demo with live log appending.

Usage: python3 run.py [--addr :9514] [--interval 2.5] [--burst 3]
                      [--viewer /path/to/minilog-web-viewer]

  --addr      Address for the web viewer to listen on  (default: :9514)
  --interval  Average seconds between appended batches (default: 2.5)
  --burst     Max entries per appended batch           (default: 3)
  --viewer    Explicit path to the minilog-web-viewer binary

The script searches for the binary in:
  1. The path given by --viewer (if provided)
  2. build/linux-debug/bin/    (cmake linux-debug preset)
  3. build/linux-release/bin/  (cmake linux-release preset)
  4. src/web-viewer/           (in-place 'go build' output)
"""

import argparse
import os
import subprocess
import sys
import threading

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, "../../.."))

BINARY_NAME = "minilog-web-viewer"
# Search order: cmake linux-debug, cmake linux-release, in-place 'go build'
SEARCH_DIRS = [
    os.path.join(REPO_ROOT, "build", "linux-debug", "bin"),
    os.path.join(REPO_ROOT, "build", "linux-release", "bin"),
    os.path.normpath(os.path.join(SCRIPT_DIR, "..")),
]


def find_viewer(explicit: str | None) -> str:
    if explicit:
        if not os.path.isfile(explicit):
            sys.exit(f"error: --viewer path not found: {explicit}")
        return os.path.abspath(explicit)

    for d in SEARCH_DIRS:
        candidate = os.path.join(d, BINARY_NAME)
        if os.path.isfile(candidate):
            return os.path.abspath(candidate)

    searched = "\n  ".join(SEARCH_DIRS)
    sys.exit(
        f"error: '{BINARY_NAME}' not found in any of:\n  {searched}\n"
        f"Build with cmake --build build/linux-debug, "
        f"or pass --viewer /path/to/{BINARY_NAME}."
    )


def write_config(addr: str) -> str:
    """Generate demo/minilog.conf with absolute log paths, and return its path.

    minilog rejects a relative text_file / jsonl_file, so the demo config cannot
    be a checked-in file: the paths depend on where the repository was cloned.
    Generating it next to this script keeps the demo relocatable.

    The listen address goes in here too — the viewer has no --addr flag; it
    reads [web_viewer] out of minilog.conf like every other deployment fact.
    """
    host, _, port = addr.rpartition(":")
    if not port.isdigit():
        sys.exit(f"error: --addr must end in ':<port>', got {addr!r}")
    logs_dir = os.path.join(SCRIPT_DIR, "logs")
    config_path = os.path.join(SCRIPT_DIR, "minilog.conf")
    sections = [
        ("main", "syslog", "100MB", "*", "true"),
        ("auth", "auth", "50MB", "auth,authpriv", "false"),
    ]
    lines = [
        "; minilog-web-viewer demo configuration — generated by run.py, do not edit.",
        "[server]",
        "host = 127.0.0.1",
        "udp_port = 5140",
        "workers = 2",
    ]
    for name, stem, max_size, facility, malformed in sections:
        lines += [
            "",
            f"[output.{name}]",
            f"text_file  = {os.path.join(logs_dir, stem + '.log')}",
            f"jsonl_file = {os.path.join(logs_dir, stem + '.jsonl')}",
            f"max_size   = {max_size}",
            "max_files  = 5",
            f"facility   = {facility}",
            f"include_malformed = {malformed}",
        ]
    lines += ["", "[web_viewer]", f"host = {host}", f"port = {port}"]
    with open(config_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return config_path


def run_appender(interval: float, burst: int, stop_event: threading.Event) -> None:
    """Run append_data as a subprocess on a background thread."""
    proc = subprocess.Popen(
        [
            sys.executable,
            os.path.join(SCRIPT_DIR, "append_data.py"),
            "--interval",
            str(interval),
            "--burst",
            str(burst),
        ],
        stderr=sys.stderr,
    )
    stop_event.wait()
    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--addr", default=":9514", help="listener address for the web viewer (default: :9514)"
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=2.5,
        help="average seconds between appended batches (default: 2.5)",
    )
    parser.add_argument(
        "--burst", type=int, default=3, help="max entries per appended batch (default: 3)"
    )
    parser.add_argument(
        "--viewer", default=None, help="explicit path to the minilog-web-viewer binary"
    )
    args = parser.parse_args()

    viewer_bin = find_viewer(args.viewer)
    config_path = write_config(args.addr)

    # (Re-)generate the initial data set.
    print("Generating test data...", flush=True)
    subprocess.run(
        [sys.executable, os.path.join(SCRIPT_DIR, "gen_data.py")],
        check=True,
    )

    # Start the appender on a background thread (runs as a subprocess internally).
    stop_event = threading.Event()
    appender_thread = threading.Thread(
        target=run_appender,
        args=(args.interval, args.burst, stop_event),
        daemon=True,
    )
    appender_thread.start()

    print(f"Starting {BINARY_NAME}...", flush=True)
    try:
        subprocess.run(
            [viewer_bin, "--config", config_path],
            check=False,
        )
    except KeyboardInterrupt:
        pass
    finally:
        stop_event.set()
        appender_thread.join(timeout=7)
        print("Stopped.")


if __name__ == "__main__":
    main()
